---
site:
  domain: 'lemp-wordpress.local'
  title: 'WP Local'

ssh:
  user: 'vagrant'
  group: 'vagrant'
  home: '/home/vagrant'

nginx:
  user: 'www-data'
  group: 'www-data'
  sendfile: 'off'
  port: '80'
  dir: '/var/www'

php:
  appname: 'wordpress'
  user: 'www-data'
  group: 'www-data'
  listen: '/var/run/php5-fpm.sock'
  ppa: 'ondrej/php5-5.6'
  ini:
    upload_max_filesize: '64M'
    date_timezone: 'America/Argentina/Buenos_Aires'

mysql:
  host: '127.0.0.1'
  port: '3306'
  user: 'dbuser'
  pass: 'dbpass'
  rootpass: 'rootpass'

wordpress:
  dir: '/var/www'
  user: 'wpadmin'
  pass: 'wppass'
  email: 'wpadmin@wordpress.local'
  db_name: 'wordpress'
  db_user: 'dbuser'
  db_pass: 'dbpass'
  db_host: 'localhost'
  debug: false
